apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: init
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./
    repoURL: https://github.com/jorgenpersson59/jp-argocd-mq
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
